version: '3.8'

services:
  whisper-en-1:
    image: ghcr.io/colmanfinals/colmanfinals/speech-to-text:latest
    ports:
      - "5000:4000"
    environment:
      MODEL_LANGUAGE: en
      GOOGLE_API_KEY:
      PYTHONPATH: /usr/src/app/src
      GROQ_API_KEY:
      SUPPORTED_COMMANDS: play, pause, stop, next, previous, mute, unmute, volume up, volume down, fullscreen, exit fullscreen, loop, exit
      MODELS_DICT: >
        {"en": "/whisper-small", "he": "/whisper-hebrew"}

    volumes:
      - ./uploads1:/app/uploads
      - /home/st111/whisper-small:/whisper-small
      - /home/st111/whisper-large-v2-tuned:/whisper-hebrew
  whisper-en-2:
    image: ghcr.io/colmanfinals/colmanfinals/speech-to-text:latest
    ports:
      - "5001:4000"
    environment:
      SUPPORTED_COMMANDS: play, pause, stop, next, previous, mute, unmute, volume up, volume down, fullscreen, exit fullscreen, loop, exit
      MODEL_LANGUAGE: en
      PYTHONPATH: /usr/src/app/src
      GOOGLE_API_KEY:
      GROQ_API_KEY:
      MODELS_DICT: >
        {"en": "/whisper-small", "he": "/whisper-hebrew"}
    volumes:
      - ./uploads2:/app/uploads
      - /home/st111/whisper-small:/whisper-small
      - /home/st111/whisper-large-v2-tuned:/whisper-hebrew
  whisper-he-1:
    image: ghcr.io/colmanfinals/colmanfinals/speech-to-text:latest
    ports:
      - "5002:4000"
    environment:
      SUPPORTED_COMMANDS: play, pause, stop, next, previous, mute, unmute, volume up, volume down, fullscreen, exit fullscreen, loop, exit
      MODEL_LANGUAGE: he
      GROQ_API_KEY:
      PYTHONPATH: /usr/src/app/src
      GOOGLE_API_KEY:
      MODELS_DICT: >
        {"en": "/whisper-small", "he": "/whisper-hebrew"}
    volumes:
      - ./uploads3:/app/uploads
      - /home/st111/whisper-small:/whisper-small
      - /home/st111/whisper-large-v2-tuned:/whisper-hebrew
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/st111/cert/server.crt:/etc/nginx/server.crt
      - /home/st111/cert/server.key:/etc/nginx/server.key
    depends_on:
      - whisper-en-1
      - whisper-en-2
      - whisper-he-1
