name: Build Docker Image

on:
  push:
    branches:
      - main  # Adjust this as necessary for your workflow needs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Get current datetime
      id: datetime
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/speech-to-text-guidetube:${{ steps.datetime.outputs.date }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
